### ISSUE TITLE
Trying this after Sep 17, 2018 and getting a missing file?

### ISSUE THREAD

**Issue by lacanlale** [llSourcell/tensorflow_image_classifier#19]
Just want to point out that the retrain.py file was moved **out** of the original tensorflow repo and into the hub repo @ https://github.com/tensorflow/hub/blob/master/examples/image_retraining/retrain.py

**Comment by cvagg** [comment]
Amazing! Been trying to figure this out for ages! How can I pull the files from this repository?

**Comment by lacanlale** [comment]
Hello! I don't want to be "that dev" and leave you hanging but I will say that it's been quite some time since I've last used this so I don't entirely remember what I exactly used here. My best guess would be to pull the retrain file from the link above and place it where its needed. I will say that it seems like this repo hasn't been updated for quite some time and my suggestion is a bit of a shot-in-the-dark so it'd probably best to find something a little more up to date. I hope this helps!
